In [1]:
import numpy as np

In [11]:
from pprint import pprint

In [2]:
a= np.arange(0,9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
b=np.array(a).reshape([3,3])
b


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
b.mean(0)

array([3., 4., 5.])

In [12]:
def calculate(arr):
    if len(arr) != 9:
        raise ValueError("List must contain nine numbers.")

    m = np.array(arr).reshape([3, 3])
    r = {
        "mean": [m.mean(0).tolist(), m.mean(1).tolist(), m.mean()],
        "variance": [m.var(0).tolist(), m.var(1).tolist(), m.var()],
        "standard deviation": [m.std(0).tolist(), m.std(1).tolist(), m.std()],
        "max": [m.max(0).tolist(), m.max(1).tolist(), m.max()],
        "min": [m.min(0).tolist(), m.min(1).tolist(), m.min()],
        "sum": [m.sum(0).tolist(), m.sum(1).tolist(), m.sum()],
    }
    return r

In [13]:
pprint(calculate([i for i in range(0, 9)]))

{'max': [[6, 7, 8], [2, 5, 8], 8],
 'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0],
 'min': [[0, 1, 2], [0, 3, 6], 0],
 'standard deviation': [[2.449489742783178,
                         2.449489742783178,
                         2.449489742783178],
                        [0.816496580927726,
                         0.816496580927726,
                         0.816496580927726],
                        2.581988897471611],
 'sum': [[9, 12, 15], [3, 12, 21], 36],
 'variance': [[6.0, 6.0, 6.0],
              [0.6666666666666666, 0.6666666666666666, 0.6666666666666666],
              6.666666666666667]}
